[tool.poetry]
name = "doglib"
description = "Digital Object Gate Python library"
version = "1.0.4"
authors = [
    "Michał Gawor <m.j.gawor@uu.nl>"
]

packages = [
    { include = "doglib" }
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
certifi = "*"
lxml = ">=4.6"
pycurl = ">=7.43.0"



